src/authority/authority/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from ou.views import IndexView

urlpatterns = [
    re_path(r'^$', IndexView.as_view(), name='index'),
    path('ou/', include('ou.urls')),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
]

src/authority/ou/urls.py
"""
This module holds the URL endpoints of the application.

API-endpoints are defined in the router.
GUI-endpoints are defined in the urlpatterns.
"""

from django.urls import path, include
from . import views
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'signatures', views.SignaturesViewSet)
router.register(r'keys', views.KeysViewSet)

app_name = 'ou'
urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('signature_list/', views.IndexView.as_view(), name='index'),
    path('verify_result/', views.verify_signature, name='verify_result'),
    path('verify/', views.VerifyView.as_view(), name='verify'),
    path('sign/', views.upload_file, name='sign'),
    path('keys2/', views.Keys_View, name='keys2'),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include('users.urls')),
]

src/authority/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'
urlpatterns = [
    path('login_user', views.login_user, name="login"),
    path('logout_user', views.logout_user, name="logout"),
    path('register_user', views.register_user, name="register_user"),
]

src/authority/ou/models.py
"""
This module holds the models used by the application:
* Platform
* Keys
* Signatures
"""

from django.db import models
from django.contrib.auth.models import User

class Platform(models.Model):
    """
    The Platform-model contains the platofrm where the key is used
    """

    platform_name = models.CharField(max_length=100)
    """platform_name: The name of the platform"""

    def __str__(self):
        return self.platform_name

class Keys(models.Model):
    """
    The Keys-model holds the public and private keys.
    """
    key = models.CharField(max_length=512)
    """key: the key"""

    role = models.CharField(max_length=64)
    """role: either public or private"""

    platform_used = models.ForeignKey(Platform, on_delete=models.CASCADE)
    """platform_used: the platform where this key is used"""

    owner = models.ForeignKey(User, on_delete=models.RESTRICT)
    """owner: the user that owns this key"""
    
    def __str__(self):
        return self.key

class Signatures(models.Model):
    """
    The Signatures-model hold the signatures that were generated for
    the uploaded files.
    """

    key_used = models.ForeignKey(Keys, on_delete=models.CASCADE)
    """key_used: reference to the key of the Keys-model"""

    file_name = models.CharField(max_length=100)
    """file_name: file name on the filesystem"""

    digest = models.CharField(max_length=512) 
    """digest: hash value of the file"""

    salt = models.CharField(max_length=128)
    """salt: string used for salting the encryption algorithm"""

    signature = models.CharField(max_length=512)
    """signature: the calculated signature"""

    time_stamp = models.DateTimeField('date signed')
    """time_stamp: the timestamp of signing"""
    
    def __str__(self):
        return self.file_name

src/authority/ou/views.py
"""
This module contains frontendviews and gives an implementation of the API-endpoints.
"""
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.shortcuts import get_object_or_404, render
from .models import Signatures, Keys
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from datetime import datetime
from django.conf import settings
from django.core.files.storage import FileSystemStorage

from django.contrib.auth.models import User, Group

from rest_framework import viewsets
from rest_framework import permissions
from .serializers import SignaturesSerializer, KeysSerializer

import ecdsa
from ecdsa import SigningKey, VerifyingKey
from hashlib import sha256

import os.path
from os import path

from django.conf import settings


class IndexView(generic.ListView):
    """
    Index views, shows the latest signatures.
    """
    template_name = 'ou/index.html'
    context_object_name = 'latest_signature_list'

    def get_queryset(self):
        return Signatures.objects.all()


class VerifyView(generic.ListView):
    """
    View to verify signature.
    """
    model = Signatures
    template_name = 'ou/verify.html'


class SignView(generic.ListView):
    """
    View to sign documents.
    """
    model = Signatures
    template_name = 'ou/sign.html'

class KeyView(generic.ListView):
    model = Keys
    template_name = 'ou/keys.html'
    context_object_name = 'my_public_keys'

def Keys_View(request):
   
    public_keys = Keys.objects.filter(role='public')
    return render(request, 'ou/keys2.html', {'public_keys': public_keys})

   
def verify_signature(request):
    """
    Verifies signature of a given filename. Both the filename and the signature
    should be given. The given signature will be matched against the key in the
    database. 

    Args:
        request.POST['file_name']: The filename of the file on the filesystem of the server
        request.POST['signature']: The signature to test against

    Returns:
        Returns a redirect to ou/verify.html with the result of the verification.
    """
    file_name = request.POST['file_name']
    signature = request.POST['signature']

    complete_path = os.path.join(settings.BASE_DIR, "ou/upload/" + file_name)
    if path.exists(complete_path) == False or file_name == "" or signature == "":
        return render(request, 'ou/verify.html', {'uploaded_file_url': "Empty field or error"})

    file = open(complete_path, 'rb')
    file_bytes = file.read()

    # obtain public key from database
    public_key = get_object_or_404(Keys, pk=2)
    vk_import = VerifyingKey.from_string(bytes.fromhex(
        public_key.key), curve=ecdsa.SECP256k1, hashfunc=sha256)

    try:
        verify_result = vk_import.verify(bytes.fromhex(signature), file_bytes)
    except:
        return render(request, 'ou/verify.html', {'uploaded_file_url': "Failed verification"})

    return render(request, 'ou/verify.html', {'uploaded_file_url': str(verify_result)})


def upload_file(request):
    """
    Uploads file, saves file to filesystem, signs file and 
    stores signature in database.

    Args:
        request: Django request-object. request.FILES is used to handle the upload

    Returns:
        Returns a redirect to ou/sign.html with the new uploaded
        file on success (otherwise redirect to ou/sign.html without
        that file).
    """
    if request.method == 'POST' and request.FILES['myfile']:
        myfile = request.FILES['myfile']
        fs = FileSystemStorage()
        filename = fs.save(myfile.name, myfile)
        uploaded_file_url = fs.url(filename)

        # obtain signature here

        complete_path = os.path.join(
            settings.BASE_DIR, "ou/upload/" + myfile.name)
        if path.exists(complete_path) == False:
            return HttpResponse("File does not exist.")

        file = open(complete_path, "ab+")
        current_time = timezone.now()
        date_string = datetime.strftime(current_time, '%d-%m-%Y %H:%M:%S')
        date_bytes = bytes("\nDate signed: " + date_string, 'utf-8')

        file.write(date_bytes)
        file_bytes = file.read()

        # obtain private key from database

        private_key = get_object_or_404(Keys, pk=1)
        sk_import = SigningKey.from_string(bytes.fromhex(
            private_key.key), curve=ecdsa.SECP256k1, hashfunc=sha256)

        # sign the document

        sig = sk_import.sign(file_bytes).hex()

        # store result in database

        signature = Signatures(key_used=private_key, file_name=myfile.name,
                               digest="test", salt="test", signature=sig, time_stamp=current_time)
        signature.save()

        # return signature to user

        return render(request, 'ou/sign.html', {
            'uploaded_file_url': sig
        })
    return render(request, 'ou/sign.html')


class SignaturesViewSet(viewsets.ModelViewSet):
    """
    API endpoint for signatures.
    """
    queryset = Signatures.objects.all().order_by('id')
    serializer_class = SignaturesSerializer
    permission_classes = [permissions.IsAuthenticated]

class KeysViewSet(viewsets.ModelViewSet):
    """
    API endpoint for keys.
    """
    queryset = Keys.objects.all().order_by('id')
    serializer_class = KeysSerializer
    permission_classes = [permissions.IsAuthenticated]

src/authority/ou/templates/ou/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'ou/style.css' %}">

<h1>Signing Authority Application</h1>

{% if user.is_authenticated %}

    <p><a href="{% url 'users:logout' %}"><h4>Click here to logout</h4></a></p>

{% else %}

    <p><a href="{% url 'users:login' %}"><h4>Click here to login</h4></a></p>
    <p><a href="{% url 'users:register_user' %}"><h4>Click here to register</h4></a></p>

{% endif %}

<p><a href="{% url 'ou:sign' %}"><h4>Click here to obtain a signature on a document</h4></a></p>
<p><a href="{% url 'ou:verify' %}"><h4>Click here to verify a signature</h4></a></p>
<p><a href="{% url 'ou:keys2' %}"><h4>Click here for your keys.</h4></a></p>


<h2>List of signatures</h2>

{% if latest_signature_list %}

    {% for s in latest_signature_list %}
<h4>Signature: {{ s.id }} generated {{ s.time_stamp }}</a></h4>

    <div class="page">        <ul>
            <li><p class="signature">{{ s.file_name }}</p></li>
            <li><p class="signature">{{ s.signature }}</p></li>
        </ul></div><br>
    {% endfor %}
    </ul>
{% else %}
    <p>No signatures available.</p>
{% endif %}

src/authority/ou/templates/ou/keys2.html
{% load static %}         
                                            
<link rel="stylesheet" type="text/css" href="{% static 'ou/style.css' %}">   

<h2>List of keys</h2>
<ul>
    {% for key in public_keys %}
        <li>{{ key.key }}</li>
    {% endfor %}
</ul>

src/authority/ou/templates/ou/sign.html
{% load static %}                                                     
<link rel="stylesheet" type="text/css" href="{% static 'ou/style.css' %}">   

<h1>Obtain a signature of a document</h1>

    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

        <input type="file" name="myfile">
        <input type="submit" value="Sign now">
    </form>

      {% if uploaded_file_url %}
      <div class="page"><p class="signature">{{ uploaded_file_url }}</p></a></div>
  {% endif %}

  <p><a href="{% url 'ou:index' %}"><h4>Check the list of signatures</h4></a></p>

src/authority/ou/templates/ou/verify.html
{% load static %}

   
<link rel="stylesheet" type="text/css" href="{% static 'ou/style.css' %}">   


<h1>Verify a signature</h1>

    <form action="{% url 'ou:verify_result'  %}" method="post">
    {% csrf_token %}
    <label for="file_name">File name: </label>
    <input id="file_name" type="text" name="file_name" value="{{ current_name }}">
    <label for="signature">Signature: </label>
    <input id="signature" type="text" name="signature" value="{{ current_signature }}">

    <br><br>
    <input type="submit" value="Verify">
    </form>

    {% if uploaded_file_url %}
    <div class="page"><p class="signature">{{ uploaded_file_url }}</    p></a></div>
   {% endif %}

    <h4>Click on "Verify" to validate a signature</h4>

   <p><a href="{% url 'ou:index' %}"><h4>Check the list of signatures</h4></a></p>